apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cm
  labels:
    app.kubernetes.io/name: argocd-ephemeral-access
    app.kubernetes.io/managed-by: kustomize
# data:
  ## Log configurations
  # backend.log.level: info
  # backend.log.format: json

  ## The API server port
  # backend.port: '8888'

  ## The address the metric endpoint binds to
  # backend.metrics.port: 8091

  ## Defines the default duration to be used when creating AccessRequests
  # backend.defaultAccessDuration: 4h